name: Build and Deploy to Azure
on:
  push:
    branches:
      - github-actions # for debug
    tags:
      - v*

env:
  AZURE_WEBAPP_NAME: live-share-editor
  AZURE_WEBAPP_PACKAGE_PATH: 'build'
  NODE_VERSION: '10.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Replace latest version tag
      run: sed -i -e s/LATEST_RELEASE_VERSION_TAG/$(git describe --abbrev=0 --tags)/ ./ClientApp/src/components/NavMenu.js
    - name: Publish with dotnet
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
